# Generated by Django 5.2 on 2026-04-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('time_slot', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
