# Generated by Django 5.2 on 2026-04-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(choices=[('🏸', 'Badminton'), ('🎾', 'Tennis'), ('⚽', 'Football'), ('⛸️', 'Skating'), ('♟️', 'Chess'), ('🏊', 'Swimming'), ('🏓', 'Table Tennis'), ('🥊', 'Boxing'), ('🤸', 'Gymnastics'), ('🏋️', 'Weightlifting'), ('🎯', 'Archery'), ('🏐', 'Volleyball'), ('🏀', 'Basketball'), ('🎱', 'Billiards'), ('🥋', 'Martial Arts')], default='🏸', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
