# Generated by Django 5.2 on 2026-04-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('batch_type', models.CharField(choices=[('regular', 'Regular'), ('alternate', 'Alternate'), ('day_based', 'Day-Based'), ('weekend', 'Weekend'), ('intensive', 'Intensive'), ('custom', 'Custom')], default='regular', max_length=20)),
                ('days_per_week', models.PositiveSmallIntegerField(choices=[(1, '1 day / week'), (2, '2 days / week'), (3, '3 days / week'), (4, '4 days / week'), (5, '5 days / week'), (6, '6 days / week'), (7, '7 days / week')], default=6)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpertiseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Display order (1 = first / most basic)')),
                ('description', models.TextField(blank=True)),
                ('color_hex', models.CharField(default='#3A7A52', help_text='Hex color used for UI badge, e.g. #3A7A52', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expertise Level',
                'verbose_name_plural': 'Expertise Levels',
                'ordering': ['order', 'name'],
            },
        ),
    ]
