# Generated by Django 5.2 on 2026-04-14 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.duration')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expertiselevel')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sport')),
            ],
            options={
                'unique_together': {('sport', 'batch', 'expertise', 'duration')},
            },
        ),
    ]
