# Generated by Django 5.2 on 2026-04-16 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feestructures_delete_feestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('NK', 'Not Known')], default='NK', max_length=4)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_relation', models.CharField(default='Father', max_length=30)),
                ('parent_whatsapp', models.CharField(max_length=15)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('parent_occupation', models.CharField(blank=True, max_length=80)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('admission_date', models.DateField()),
                ('subscription_start', models.DateField()),
                ('subscription_expiry', models.DateField()),
                ('time_slot', models.CharField(blank=True, max_length=50)),
                ('fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.batch')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.duration')),
                ('expertise_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.expertiselevel')),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.feestructures')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.sport')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
