# Generated by Django 5.2 on 2026-04-18 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coaches/photos/')),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('joining_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance / Visiting'), ('contract', 'Contract')], default='full_time', max_length=15)),
                ('salary_type', models.CharField(choices=[('fixed', 'Fixed Monthly'), ('per_batch', 'Per Batch'), ('hourly', 'Hourly')], default='fixed', max_length=15)),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emergency_name', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_relation', models.CharField(blank=True, max_length=40)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='coaches/docs/')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='coaches/docs/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expertise_levels', models.ManyToManyField(blank=True, related_name='coaches', to='core.expertiselevel')),
                ('sports_coached', models.ManyToManyField(blank=True, related_name='coaches', to='core.sport')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='studentdata',
            name='assigned_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.coach'),
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach')], default='coach', max_length=10)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='core.coach')),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10)),
                ('assigned_slot', models.CharField(blank=True, max_length=50)),
                ('attended_slot', models.CharField(blank=True, max_length=50)),
                ('is_override', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('qr', 'QR Scan')], default='manual', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.studentdata')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendance_marked', to='core.systemuser')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendance',
                'ordering': ['-date', 'student__first_name'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CoachPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('student_list', 'View Students'), ('student_admission', 'Admit Students'), ('attendance', 'Mark Attendance'), ('notifications', 'View Notifications'), ('fee_structure', 'View Fee Structure'), ('reports', 'View Reports'), ('coach_list', 'View Coaches')], max_length=30)),
                ('allowed', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.systemuser')),
            ],
            options={
                'verbose_name': 'Coach Permission',
                'verbose_name_plural': 'Coach Permissions',
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='CoachAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('on_leave', 'On Leave')], default='present', max_length=10)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('qr', 'QR Scan')], default='manual', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.coach')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_attendance_marked', to='core.systemuser')),
            ],
            options={
                'verbose_name': 'Coach Attendance',
                'verbose_name_plural': 'Coach Attendance',
                'ordering': ['-date', 'coach__first_name'],
                'unique_together': {('coach', 'date')},
            },
        ),
    ]
