# Generated by Django 5.2 on 2026-05-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Visit',
            },
        ),
        migrations.AlterField(
            model_name='coachpermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('student_list', 'View Students'), ('student_admission', 'Admit Students'), ('attendance', 'Mark Attendance'), ('notifications', 'View Notifications'), ('fee_structure', 'View Fee Structure'), ('reports', 'View Reports'), ('coach_list', 'View Coaches'), ('Payments', 'View Payment Status')], max_length=30),
        ),
    ]
