# Generated by Django 5.2 on 2026-06-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitevisit_alter_coachpermission_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
    ]
