# Generated by Django 5.2 on 2026-06-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studentdata_is_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
